_help:
  @just -l

init:
  #!/bin/bash
  set -euo pipefail

  rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
  rustup target add aarch64-apple-darwin x86_64-apple-darwin
  rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
  rustup target add x86_64-unknown-linux-gnu
  #@if os() == "macos" { cargo install cargo-lipo }
  cargo install cargo-lipo
  cargo install cbindgen
  cargo install cargo-ndk

jvm-clean:
  #!/bin/bash
  set -euo pipefail

  rm -rf ffi/jvm

jvm: jvm-clean
  #!/bin/bash
  set -euo pipefail

  cargo build --release
  cargo run -p uniffi-bindgen generate --library ../../target/release/libdap_ffi.dylib --language kotlin --no-format -o ffi/jvm